language: scala
jdk:
- oraclejdk8
script:
- mkdir -p $HOME/.triplequote && echo "${HYDRA_LICENSE}" > "$HOME/.triplequote/hydra.license"
- cat $HOME/.triplequote/hydra.license
- sbt test
env:
  matrix:
    secure: TyanGbXyYqSg8RX+Ibyh4mxTEHxJhZ7GjhoeF5Pg8sNgxVEZwsLEhOcajzIhFbXNpV4SyrGNijy/lRAUEz7sys6bFTgm+X94+Smxhjs7cUj4N9EzP8mXcO/xnYPKFaHcmLJCl3hgFXnZ71kLb2krr1NC7AJV60owSOccNNkAhyJXJzebZShtkL2a3d4N8AhQgk4C+5GiWYJ0j+3RlWYShp4l687Wxn0tgNJNKy6l9nRmm4PPaQ8/ijbxo1Nfq779IOK3FzHn78bMqBEu25pHp13/Fu0439eahc0GYt08r5L9XvfWvjFgE4gM5L01pB/LRw8HFQnjq6sotmD4DhXe9tzPBx+Y/+5ruZmWRmjzumUGrkWW2SA0G7LPNoHiUyXsuSwGgU4OUanXoGk0G4oPQAeQRqkR+ABLp3mMp4dssK6O0pOuRoGkf5P/b/sLFyKx/KKxzjlmkyyKeiBmYgCY0JRfr0296Lk6uaGe9X4ehyWhguVkqNrZUiXcUVPIRORMUn8QZqyMTY44CThYk93F4aX5t07/SMAxpANlB/E3xlJZ91n/pSAPwu46eWeKrhdavKVg9sYYVQtUv1dHj08doXfLWI3fGLsnAevktsumEhj/0TDhucCJg9YeG7b9CtrqbsqIbCpbQKkBLchmUToRVMInhpIQd6NZXyTKjP2pYgo=
