language: scala
jdk:
- oraclejdk8
script:
- mkdir -p $HOME/.triplequote && echo "${HYDRA_LICENSE}" > "$HOME/.triplequote/hydra.license"
- cat $HOME/.triplequote/hydra.license
- sbt test
env:
  global:
    secure: E3P6J41WwPhkLRFnjBI7ns9GLhg/xtu+vi7V3k6YF/n0nCyAMkYlUlU4ONdPzIOWrwcEiAAyFPws1djCtqucp3kgpZUJokp9UgHslkKJCgM8tsaoqZc8tkGKhoxtsYaY/jddmnV7azbVmNbFMIAeCxgZr7thzkvSksWhmZach72cHPRVFYt8G9qk9sUoRESCh163supIv2QYYun/Lpvr913HGzKY3+pQ2vQAAHzIFFTpOBEn24wUUmKU+frX3Caw69cu5yFcsR3QVxmgZb5c35FWVcWnxOOpZskwbdHJ89MTDEi+hfEGEhDJmqjwU/EY5Ubs/QLDo80QH9p4ysAOT8NiRCTrIEZz9DlD3GkMahFqlR0csHvF5TfX/Yd2tkbfpyi5qJoKKBAcMKVNfaP2c6cRDO3stHsfXhjtCyj5i7c5KpC7/Vls7W6nY8XoVlrMytUXMMgk+3kSzxcXjXOX+RG3nsCOPYJYvkI2+npFkRgpxjr/11WrXsIK4eoawrKE/9Y0wsBrTaeYgeHZUJKwSEMSwFFnZmLYkG752zicmGFv6hniF8aZluFswFkcqssu1qOvslh5mHxyaIudHC2vUYuXCK7dBYl23DN6SA/RNP38bu/Snp+7ZqPALpUJcNSQBrI9BwYPw3JB8FYGS4jVwzd4RFQdc8EwDUJXo4S5tnQ=
