language: scala

jdk:
  - oraclejdk8

script:
  - mkdir -p $HOME/.triplequote && echo "${HYDRA_LICENSE}" > "$HOME/.triplequote/hydra.license"
  - sbt test

env:
  matrix:
    secure: Wc7VdvS339DR/+jLLuvKbaLsTwARsz/WZKiV1ur9s56s2Li+nzjNVLfmLaqJ6vBfnjEpHjjp8qgllB7s+9rJl/Hs5f6uHuuMtjzkMhS6osraQjLCC7TI2oU7/x0fqqHLLCXsmoQmpVSldrMYhIw4IpiWne1FNOS2vqoJpDRnZVxnFeIkDsrz+Fq/Rs2xKvhTqBdQhw6Xd1q6wxBckjUPl3onwooJlubCnK6KOx80O7moowZjAAm9RagHSMYvHBdJvz6Fiuiyal6yUdkfCJFWF9NRu2b0QfkOLDDRueIpCQdBtev2nUH62mrgTj6snxIcEk/gQ0XnCSZFlyzbvqxZQ1EVWVqccADxwKJhPLY2eUiV3LggCpU0vC4Cz2mbuL7/23uVeYaZKf/Y2IJCOb6zXIoSJQwP04ywWPVKAvlnp9NiTfH6OpuQwbRKVEHlTM764xiRIMAjzHCWlb6jmdg4n38sXzc6jwvVDH98N5DQ5qtbtPDFn429L+NdKSfd9RaNftHtSA9jPfhfG2HepNcKktn5GLp+HC3eERYEFfq/B6tSp8XJ7SVDMUxEtjiiJaFPqvgYm3GIrlxjimkEGjZ8Ufs9ppJaTUlLqzH0d6FHachpMrXS9bx2VRDehLuGWG3wxx1sCMa/vOliEPcFfDOITJm8G+r/Tf7uHHWq09MjX+k=
